server:
  port: 8080

# MySQL 数据库配置
spring:
  datasource:
    url: ENC(JPbjZhYjE9DJ9zSe5XQNOb9Jd3LY0p66weO5iAdq/j8Ovt8L/TjEZxtKldE71RtedMsUwLPVYZWC+SKndafPUvXvF5owQa8k0GlTiUVZtoBG5ercFrqFInwS8LiBwmWEfPipJgmWzlXVxHwYaQO4cZuSUV+esJg07vJYNHX4ZXaVRlStACIYUSFez/fLb6L/VF+rMyUe6KnnerNiuFcCif15KlubVb655TdrveLiZD8bXDkJGcZGMw4vWRHG/3lBI6DdqB7EIFHAamAC8K3y69N3icV2to1mrSqjvuA/FlZaZGnC5LJ8JHQrimQjYaag3lafIzbA0Fy5wtKVs4mOhcVvGmsMWtvHGoO0uT0qcCw=)
    username: ENC(WZh1D06gzJ6F2k6xFaQPDtMqoMIgZOGi)
    password: ENC(23B//z/SX+A5xNEYEtR1zGl3FJUx18mM2hitQ5lYwnE=)
    driver-class-name: com.mysql.cj.jdbc.Driver

# jasypt 密码加密配置
jasypt:
  encryptor:
    # 3.0.0 以后默认算法为：PBEWITHHMACSHA512ANDAES_256
    # 而默认算法需要JDK>=1.9或者添加 JCE (Java Cryptography Extension 无限强度权限策略文件) 支持，否则运行会出现错误
    # 方案1: 使用 jasypt 2.x 版本
    # 方案2: 加密算法替换成: PBEWithMD5AndDES，并配置 iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator